name: LaTeX Compilation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Compile LaTeX document
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Compile to PDF
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: resume.tex
        compiler: lualatex

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: resume
        path: resume.pdf

    - name: Release PDF
      uses: JasonEtco/upload-to-release@master
      with:
        args: resume.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
